# Alumno 
Pérez Gastón

## Ejercicio 01
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [1]:
#Importamos librería NumPy

import numpy as np

In [6]:
def arrayRandom ():
    print("\nGenerador de arrays aleatorio compuestos por 100 elementos")
    print("==========================================================")

    arrayAleatorio = np.random.randint(100, size=(10,10))
    
    print("\nSu array Random es:")
    print("-------------------")
    print(arrayAleatorio)
    
    mediana = np.median(arrayAleatorio)
    print("\nLa mediana de su array es =",mediana)
    
    consulta = input("¿Quiere volver a utilizar el programa?: ")

    while consulta == "si":
        arrayRandom()
        consulta = input("¿Quiere volver a utilizar el programa?: ")
    else:
        print("¡Adiós Vaquerx!")

print("Bienvenidx a este programa")
init = int(input("Para comenzar ingrese 1. Si no desea continuar, pulse 0: "))

if init == 1:
    arrayRandom()
else:
    print("La próxima será :)")


Bienvenidx a este programa
Para comenzar ingrese 1. Si no desea continuar, pulse 0: 1

Generador de arrays aleatorio compuestos por 100 elementos

Su array Random es:
-------------------
[[85  5 67 89 61 87 78 65  7 59]
 [87 32 93 65 86 87  2 60 96 11]
 [97  3 62 59 63 53 57 15 35 44]
 [16 38 49 80 68 86 95 29 49 91]
 [17 46 97 23 59  0  0 19 57  7]
 [31 87 81 30  5 85 71 87 38 10]
 [ 2 37 64 18 49 74 10  3 32 38]
 [ 1 81 17 62 77 23  1 72 75 75]
 [70 31 44 64 27 10 13 12 44 60]
 [72 14 31 13 22 17 20  3 53 84]]

La mediana de su array es = 49.0
¿Quiere volver a utilizar el programa?: no
¡Adiós Vaquerx!


## Ejercicio 02
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

## Ejercicio 03
En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.